<a href="https://colab.research.google.com/github/vera-rykalina/DeepLearning-MXC/blob/main/Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python for Deep Learning - Functions

# Inputs and Outputs

In [ ]:
# Function sum()
sum([25, 35, 45])

105

In [ ]:
alist = [25, 35, 45]
sum(alist)

105

In [ ]:
# output = function(input)

## Practice

- compute the mean (average) of a variable


In [ ]:
myvariable = [2, 5, 7, 10, 7, 8, 10, 11]
print(len(myvariable))
print(sum(myvariable))
mean = sum(myvariable)/len(myvariable)
print(f"This is average of my variable: {mean}")

8
60
This is average of my variable: 7.5


# Numpy

In [ ]:
# Import a library
import numpy as np

In [ ]:
numbers = list(range(20))
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
# Numpy function mean()
np.mean(numbers)

9.5

In [ ]:
# Numpy function linspace()
z = np.linspace(1, 7, 5) # returns evenly spaced numbers over a specified interval
print(z)
print(type(z))

[1.  2.5 4.  5.5 7. ]
<class 'numpy.ndarray'>


In [ ]:
# Crearing arrays
numbersNumpy = np.array(numbers)
print(type(numbers))
print(type(numbersNumpy)) 

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# Mean()
numbersNumpy.mean()

9.5

In [ ]:
# Min()
numbersNumpy.min()

0

In [ ]:
# Max()
numbersNumpy.max()

19

In [ ]:
# Some methods work on both lists numpy arrays
print(np.max(numbers))
print(np.max(numbersNumpy))

19
19


In [ ]:
# Importing a specific single function from the Numpy library
from numpy import mean # one can add "as"
mean(numbers)

9.5

## In-place/Out-of-place

- in-place operations (a variable is changing)
- out-of-place / not in-place operations

In [ ]:
# Reminder
nums = [4,2,7,4,8,6,9,8]
print(nums)
nums.sort()
print(nums)

[4, 2, 7, 4, 8, 6, 9, 8]
[2, 4, 4, 6, 7, 8, 8, 9]


In [ ]:
# Numpy method .sort()
nums = [4,2,7,4,8,6,9,8]
nXn = np.array(nums)
print(nXn)
nXn.sort()
print(nXn)

[4 2 7 4 8 6 9 8]
[2 4 4 6 7 8 8 9]


In [ ]:
# Numpy function sort()
nums = [4,2,7,4,8,6,9,8]

# It is not an in-place operation 
nXn = np.array(nums)
print(nXn)
sorted = np.sort(nXn)
print(sorted)

[4 2 7 4 8 6 9 8]
[2 4 4 6 7 8 8 9]


# Pandas

In [ ]:
# Import pandas library (datasets: observation/features)
import numpy as np
import pandas as pd
from numpy.random import randn

## Create random data

In [ ]:
# Random number generator
# Returns 5 numbersfrom normal distribution (mean = 0, sd = 1
randn(5) 

array([-1.16313553,  1.13212908,  2.22093535,  0.37631606, -1.16056251])

In [ ]:
# Create random data
# Returns 5 x 5 matrix with numbers from normal distribution (mean = 0, sd = 1)
np.random.randn(5,5) 

array([[-0.88241575,  0.05092956,  0.24711482, -0.20101259,  0.27957831],
       [ 0.1358239 , -2.2942917 ,  0.39679254,  1.38516105,  0.41648362],
       [-0.25324936, -0.79288463, -0.31399177, -0.72120678,  0.26712771],
       [-0.55542053, -0.05493844, -0.73198581,  0.32946792,  0.88809483],
       [-0.405175  ,  0.16217321, -0.69174596,  0.21260879, -0.88422547]])

In [ ]:
# Create random data
column1 = randn(80)*6 + 22
print(column1)
print("========================================================================")
column2 = randn(80) >0
print(column2)

# Create labels
labels = ["Temperature (C)", "Ice Cream"]

# Put variables together into a dictionary
D = {labels[0] : column1, labels[1] : column2}
print("========================================================================")

# Import a dictionary into pandas dataframe
df = pd.DataFrame(data = D)
print(type(df))

[20.55071681 11.47590783 10.84442728 28.65092607 32.29536413 32.05826435
 13.54095111 19.00211339 21.07484276 21.54576115 21.94665843 19.33665351
 19.25821942 20.453346   12.833125   31.94598488 20.9660871  20.92649001
 31.99247002 16.8372869  18.74680637 19.57960297 27.11726566 15.1738413
 24.73872931 21.68956219 18.16854151 32.16070351 14.32149298 29.11244283
 17.00536422 17.36453078 23.27934525 17.60977833 29.49653451 17.72985404
 22.64894848 17.32225545 21.87980346 20.41801656 31.31995129  7.77666001
 27.80278024 14.42077187 30.17094087 12.41285412 29.36601348 25.76922958
 26.82903572 26.06745159 14.63802148 24.5903792  17.75426474 19.26184344
 21.26560154 18.14012241 11.79439332 22.10637565 21.20337726 32.03388361
 25.10223434 27.23109182 18.80369159 18.80695929 21.92328063 20.3239959
  9.77748619 14.26696533 26.47657581 28.03135019 30.7195556  23.4789413
 19.09104663 12.79927006 21.7056219  19.12855428 18.28747418 11.17500778
 29.12599939 17.56142601]
[False False  True False  Tr

In [ ]:
# Call dataframe
df

Temperature (C)  Ice Cream
0         20.550717      False
1         11.475908      False
2         10.844427       True
3         28.650926      False
4         32.295364       True
..              ...        ...
75        19.128554       True
76        18.287474       True
77        11.175008      False
78        29.125999       True
79        17.561426      False

[80 rows x 2 columns]

## Dataframe methods

In [ ]:
# Method .head()
df.head() # returns 5 top rows

Temperature (C)  Ice Cream
0        20.550717      False
1        11.475908      False
2        10.844427       True
3        28.650926      False
4        32.295364       True

In [ ]:
# Method .count()
df.count() # returns number of observations for each columns

Temperature (C)    80
Ice Cream          80
dtype: int64

In [ ]:
# Method .mean()
df.mean() # returns average for each column

Temperature (C)    21.270494
Ice Cream           0.500000
dtype: float64

## Practice

Create a pandas dataframe with:

- integers going from 0 to 10, their square, and their log

In [ ]:
# Import generator function
from numpy.random import randint

In [ ]:
# Create the first column
col1 = randint(low = 0, high = 10, size = 50 )

In [ ]:
# Create a dictionary
D = {"Number": col1}

In [ ]:
# Create a dataframe
df = pd.DataFrame(data = D)

In [ ]:
# Add other columns
df["Square"] = np.square(col1)

In [ ]:
df.head()

Number  Square
0       2       4
1       2       4
2       9      81
3       2       4
4       6      36

In [ ]:
df["Log"] = 0
for num in df["Number"]:
  if num != 0:
    df.loc[df["Number"] == num, "Log"] = np.log(num).round(2)
  else:
     df.loc[df["Number"] == num, "Log"] = "Skip" 

In [ ]:
df.head(15)

Number  Square   Log
0        2       4  0.69
1        2       4  0.69
2        9      81   2.2
3        2       4  0.69
4        6      36  1.79
5        9      81   2.2
6        4      16  1.39
7        2       4  0.69
8        3       9   1.1
9        2       4  0.69
10       7      49  1.95
11       1       1   0.0
12       5      25  1.61
13       0       0  Skip
14       4      16  1.39

# Functions

## Getting help

- For SHIFT + TAB to work, you have to disable Automatically trigger code completions on Tools $\Rightarrow$ Settings $\Rightarrow$ Editor.

In [ ]:
# sum(shift + tab)
lis = [1, 3, 3]
sum(lis, 0)

7

In [ ]:
# sum?
sum?

# sum??  (more detailed)
sum??

In [ ]:
# help(function name)
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, start=0, /)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



## Creating a function

- Python keyword def (definition) is used to create a fucntion.

In [5]:
# Create a function
def myfunction ():
  print("Hi, my first function")
print("Won't be printed!")

Won't be printed!


In [6]:
myfunction()

Hi, my first function


In [13]:
# Create a function with two inputs
def my2function (input1, input2):
  print(input1 + input2)

In [14]:
my2function(input1=3, input2=4)

7


In [19]:
# Create a function with two inputs
def my3function (input1, input2):
  return input1 + input2

In [20]:
result = my3function(10, 20)
result

30

In [26]:
# Create a function with two inputs and two outputs
def my4function (input1, input2):
  summa = input1 + input2
  product = input1 * input2
  return summa, product

In [27]:
# Getting result as tuple
my4function(3, 8)

(11, 24)

In [31]:
# Extraction output from tuple
# Option one (indexing)
res = my4function(3, 8)
print(res[0])
print(res[1])

11
24


In [34]:
# Extraction output from tuple
# Option two (tuple on)
summa, product = my4function(3, 8)
print(summa)
print(product)

11
24


## Lambda function

In [37]:
# A compact sysntax for short functions
funname = lambda x: x/4 + 5

In [38]:
funname(16)

9.0

## Practice

Factorial
- create a function that computes a factorial

- compare against math.factorial()

In [103]:
# Creating a function
def myfactorial (n):
  num = 1
  factorial = 1
  if n > 0:
    while num <= n: 
      factorial *= num
      num += 1
  elif n == 0:
    factorial = 1
  else:
    print("Invalid input! n should be a positive number!")
  return factorial

In [99]:
myfactorial(5)

120

In [127]:
# Compare with a built-in function from the math library

# Import library
import math
# Set n for comparison
n=22

myfunction_result = myfactorial(n) 
print(f"My function: {n}! = {myfunction_result}")
math_result = math.factorial(n)
print(f"Math library: {n}! = {math_result}")
print(f"Do functions give the same output? Answer: {math_result == myfunction_result}")

My function: 22! = 1124000727777607680000
Math library: 22! = 1124000727777607680000
Do functions give the same output? Answer: True


# Scope

Global and local bariable scopes

In [129]:
# Use %reset -f to clear all variables in IPython
%reset -f

In [130]:
%whos

Interactive namespace is empty.


In [131]:
# Local scope
def foo ():
  x = 2 # defined locally
  y = 3 # defined locally
  print(x)

In [132]:
foo()

2


In [136]:
# Experimenting
x = 4
print(x)
foo()
print(x)

4
2
4


In [137]:
def fee():
  print(z)

In [139]:
z = 13 # global
fee()

13


## Rules

Recommendation: When creating function, try to avoid creating local variables that have the same name as variable in the global scope.

- variables created inside a fuction are local (accessible only inside the function)

- variables created outside of a function are global (accessible in or out of the function)

## Practice

Gambling experiment

Write a function that flips a coin N times, and reports the average.

Tip: use some numpy function 

In [201]:
# Definitions
# Heads = 1
# Tails = 0

In [222]:
 # Import libraries
 import random

In [267]:
random.seed(2022)
mylist = [0,1]
N = 100000
flips = [random.choice(mylist) for x in range(N)]
avg_heads = flips.count(1)/N
print(avg_heads)

0.49828


In [268]:
random.seed(2022)
def coin_flip(N):
  result = [random.choice([0,1]) for x in range(N)].count(1)/N
  print(f"{N} coin flips had {round(result*100, 1)}% heads.")

In [269]:
coin_flip(N)

100000 coin flips had 49.8% heads.


# Copies and referents of variables

In [4]:
# Example problem
a = [3, 4]
b = a
b[0] = 5 # b is a new pointe the same location in memory where a is stored 
print(a)
print(b)

[5, 4]
[5, 4]


In [5]:
# Invoke location with id() function
print(id(a)) # location of a and b is the same 
print(id(b))

140636437705184
140636437705184


In [6]:
# Not a universal solution
a = [3, 4]
b = a[:] # copying a
b[0] = 5
print(a)
print(b)

[3, 4]
[5, 4]


In [13]:
# Demonstration of a case where the above mentioned trick  a[:] will not work
a = {"k1": 3, "k2": 4}
b = a
b["key3"] = 5
print(a)
print(b)

{'k1': 3, 'k2': 4, 'key3': 5}
{'k1': 3, 'k2': 4, 'key3': 5}


## Copy library

In [15]:
# A universal solution
import copy
a = {"k1": 3, "k2": 4}
b = copy.deepcopy(a)
print(a)
print(b)

# a and b have different locations
print(id(a)) 
print(id(b))

{'k1': 3, 'k2': 4}
{'k1': 3, 'k2': 4}
140636376008736
140636376031712


# Classes and OOP

A class is a blueprint for creating a set of attributes (variables) and methods (functions)

In [39]:
# Defining a class

class model(object):
  
  # constructor method
  def __init__(self, numlayers, numunits, name):
    self.layers  = numlayers # attributes
    self.units   = numunits
    self.name    = name
    self.weights = 0
  
  # method 1
  def howManyUnits(self):
    totalUnits = self.layers * self.units
    print(f"There are {totalUnits} in the model.")
  
  # method 2
  def trainModel(self, x):
    self.weights += x
    return self.weights
  
  # method 3
  def __str__(self):
    return f"This is a {self.name} architecture."

In [41]:
# Creating an instance
m1 = model(14, 3, "CNN")
# print(m1)
# m1.howManyUnits()
str(m1) # see model()

'This is a CNN architecture.'

In [38]:
m1.trainModel(2.5) # updates 

5.0

## Practice

Create a new class with some changes:

- weights should be a random numbers matrix of size layers X units

- change training method to multiply input X and add input Y

In [180]:
import numpy as np

class practice_model(object):
  
  # constructor method
  def __init__(self, numlayers, numunits, name, randomnumber):
    self.layers  = numlayers # attributes
    self.units   = numunits
    self.name    = name
    self.randomnumber = randomnumber
    self.weights = np.random.randint(randomnumber, size=(numlayers, numunits))


  # method 1
  def howManyUnits(self):
    totalUnits = self.layers * self.units
    print(f"There are {totalUnits} in the model.")
  
  # method 2
  def trainModel(self, x, y):
    #print(self.weights)
    self.weights = self.weights * x + y
    return self.weights
  
  # method 3
  def __str__(self):
    return f"This is a {self.name} architecture."

In [181]:
# Creating an instance
pm = practice_model(numlayers = 2, numunits = 3, name ="RNN", randomnumber = 100)
pm.weights

array([[62, 78, 51],
       [57, 13, 17]])

In [182]:
pm.trainModel(2, 2)
pm.weights

array([[126, 158, 104],
       [116,  28,  36]])