<a href="https://colab.research.google.com/github/vera-rykalina/PythonIntroDeepLearning/blob/main/Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python for Deep Learning - Functions

# Inputs and Outputs

In [4]:
# Function sum()
sum([25, 35, 45])

105

In [2]:
alist = [25, 35, 45]
sum(alist)

105

In [3]:
# output = function(input)

## Practice

- compute the mean (average) of a variable


In [10]:
myvariable = [2, 5, 7, 10, 7, 8, 10, 11]
print(len(myvariable))
print(sum(myvariable))
mean = sum(myvariable)/len(myvariable)
print(f"This is average of my variable: {mean}")

8
60
This is average of my variable: 7.5


# Numpy

In [12]:
# Import a library
import numpy as np

In [14]:
numbers = list(range(20))
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [22]:
# Numpy function mean()
np.mean(numbers)

9.5

In [30]:
# Numpy function linspace()
z = np.linspace(1, 7, 5) # returns evenly spaced numbers over a specified interval
print(z)
print(type(z))

[1.  2.5 4.  5.5 7. ]
<class 'numpy.ndarray'>


In [24]:
# Crearing arrays
numbersNumpy = np.array(numbers)
print(type(numbers))
print(type(numbersNumpy)) 

<class 'list'>
<class 'numpy.ndarray'>


In [25]:
# Mean()
numbersNumpy.mean()

9.5

In [27]:
# Min()
numbersNumpy.min()

0

In [28]:
# Max()
numbersNumpy.max()

19

In [36]:
# Some methods work on both lists numpy arrays
print(np.max(numbers))
print(np.max(numbersNumpy))

19
19


In [39]:
# Importing a specific single function from the Numpy library
from numpy import mean # one can add "as"
mean(numbers)

9.5

## In-place/Out-of-place

- in-place operations (a variable is changing)
- out-of-place / not in-place operations

In [54]:
# Reminder
nums = [4,2,7,4,8,6,9,8]
print(nums)
nums.sort()
print(nums)

[4, 2, 7, 4, 8, 6, 9, 8]
[2, 4, 4, 6, 7, 8, 8, 9]


In [55]:
# Numpy method .sort()
nums = [4,2,7,4,8,6,9,8]
nXn = np.array(nums)
print(nXn)
nXn.sort()
print(nXn)

[4 2 7 4 8 6 9 8]
[2 4 4 6 7 8 8 9]


In [56]:
# Numpy function sort()
nums = [4,2,7,4,8,6,9,8]

# It is not an in-place operation 
nXn = np.array(nums)
print(nXn)
sorted = np.sort(nXn)
print(sorted)

[4 2 7 4 8 6 9 8]
[2 4 4 6 7 8 8 9]


# Pandas

In [58]:
# Import pandas library (datasets: observation/features)
import pandas as pd