<a href="https://colab.research.google.com/github/vera-rykalina/PythonIntroDeepLearning/blob/main/Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python for Deep Learning - Functions

# Inputs and Outputs

In [ ]:
# Function sum()
sum([25, 35, 45])

105

In [ ]:
alist = [25, 35, 45]
sum(alist)

105

In [ ]:
# output = function(input)

## Practice

- compute the mean (average) of a variable


In [ ]:
myvariable = [2, 5, 7, 10, 7, 8, 10, 11]
print(len(myvariable))
print(sum(myvariable))
mean = sum(myvariable)/len(myvariable)
print(f"This is average of my variable: {mean}")

8
60
This is average of my variable: 7.5


# Numpy

In [ ]:
# Import a library
import numpy as np

In [ ]:
numbers = list(range(20))
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
# Numpy function mean()
np.mean(numbers)

9.5

In [ ]:
# Numpy function linspace()
z = np.linspace(1, 7, 5) # returns evenly spaced numbers over a specified interval
print(z)
print(type(z))

[1.  2.5 4.  5.5 7. ]
<class 'numpy.ndarray'>


In [ ]:
# Crearing arrays
numbersNumpy = np.array(numbers)
print(type(numbers))
print(type(numbersNumpy)) 

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# Mean()
numbersNumpy.mean()

9.5

In [ ]:
# Min()
numbersNumpy.min()

0

In [ ]:
# Max()
numbersNumpy.max()

19

In [ ]:
# Some methods work on both lists numpy arrays
print(np.max(numbers))
print(np.max(numbersNumpy))

19
19


In [ ]:
# Importing a specific single function from the Numpy library
from numpy import mean # one can add "as"
mean(numbers)

9.5

## In-place/Out-of-place

- in-place operations (a variable is changing)
- out-of-place / not in-place operations

In [ ]:
# Reminder
nums = [4,2,7,4,8,6,9,8]
print(nums)
nums.sort()
print(nums)

[4, 2, 7, 4, 8, 6, 9, 8]
[2, 4, 4, 6, 7, 8, 8, 9]


In [ ]:
# Numpy method .sort()
nums = [4,2,7,4,8,6,9,8]
nXn = np.array(nums)
print(nXn)
nXn.sort()
print(nXn)

[4 2 7 4 8 6 9 8]
[2 4 4 6 7 8 8 9]


In [ ]:
# Numpy function sort()
nums = [4,2,7,4,8,6,9,8]

# It is not an in-place operation 
nXn = np.array(nums)
print(nXn)
sorted = np.sort(nXn)
print(sorted)

[4 2 7 4 8 6 9 8]
[2 4 4 6 7 8 8 9]


# Pandas

In [19]:
# Import pandas library (datasets: observation/features)
import numpy as np
import pandas as pd
from numpy.random import randn

## Create random data

In [13]:
# Random number generator
# Returns 5 numbersfrom normal distribution (mean = 0, sd = 1
randn(5) 

array([-1.16313553,  1.13212908,  2.22093535,  0.37631606, -1.16056251])

In [14]:
# Create random data
# Returns 5 x 5 matrix with numbers from normal distribution (mean = 0, sd = 1)
np.random.randn(5,5) 

array([[-0.88241575,  0.05092956,  0.24711482, -0.20101259,  0.27957831],
       [ 0.1358239 , -2.2942917 ,  0.39679254,  1.38516105,  0.41648362],
       [-0.25324936, -0.79288463, -0.31399177, -0.72120678,  0.26712771],
       [-0.55542053, -0.05493844, -0.73198581,  0.32946792,  0.88809483],
       [-0.405175  ,  0.16217321, -0.69174596,  0.21260879, -0.88422547]])

In [32]:
# Create random data
column1 = randn(80)*6 + 22
print(column1)
print("========================================================================")
column2 = randn(80) >0
print(column2)

# Create labels
labels = ["Temperature (C)", "Ice Cream"]

# Put variables together into a dictionary
D = {labels[0] : column1, labels[1] : column2}
print("========================================================================")

# Import a dictionary into pandas dataframe
df = pd.DataFrame(data = D)
print(type(df))

[20.55071681 11.47590783 10.84442728 28.65092607 32.29536413 32.05826435
 13.54095111 19.00211339 21.07484276 21.54576115 21.94665843 19.33665351
 19.25821942 20.453346   12.833125   31.94598488 20.9660871  20.92649001
 31.99247002 16.8372869  18.74680637 19.57960297 27.11726566 15.1738413
 24.73872931 21.68956219 18.16854151 32.16070351 14.32149298 29.11244283
 17.00536422 17.36453078 23.27934525 17.60977833 29.49653451 17.72985404
 22.64894848 17.32225545 21.87980346 20.41801656 31.31995129  7.77666001
 27.80278024 14.42077187 30.17094087 12.41285412 29.36601348 25.76922958
 26.82903572 26.06745159 14.63802148 24.5903792  17.75426474 19.26184344
 21.26560154 18.14012241 11.79439332 22.10637565 21.20337726 32.03388361
 25.10223434 27.23109182 18.80369159 18.80695929 21.92328063 20.3239959
  9.77748619 14.26696533 26.47657581 28.03135019 30.7195556  23.4789413
 19.09104663 12.79927006 21.7056219  19.12855428 18.28747418 11.17500778
 29.12599939 17.56142601]
[False False  True False  Tr

In [33]:
# Call dataframe
df

Temperature (C)  Ice Cream
0         20.550717      False
1         11.475908      False
2         10.844427       True
3         28.650926      False
4         32.295364       True
..              ...        ...
75        19.128554       True
76        18.287474       True
77        11.175008      False
78        29.125999       True
79        17.561426      False

[80 rows x 2 columns]

## Dataframe methods

In [34]:
# Method .head()
df.head() # returns 5 top rows

Temperature (C)  Ice Cream
0        20.550717      False
1        11.475908      False
2        10.844427       True
3        28.650926      False
4        32.295364       True

In [36]:
# Method .count()
df.count() # returns number of observations for each columns

Temperature (C)    80
Ice Cream          80
dtype: int64

In [37]:
# Method .mean()
df.mean() # returns average for each column

Temperature (C)    21.270494
Ice Cream           0.500000
dtype: float64

## Practice

Create a pandas dataframe with:

- integers going from 0 to 10, their square, and their log

In [70]:
# Import generator function
from numpy.random import randint

In [107]:
# Create the first column
col1 = randint(low = 0, high = 10, size = 50 )

In [108]:
# Create a dictionary
D = {"Number": col1}

In [109]:
# Create a dataframe
df = pd.DataFrame(data = D)

In [110]:
# Add other columns
df["Square"] = np.square(col1)
df["Log"] = np.log(col1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


In [106]:
df.head()

Number  Square       Log
0       5      25  1.609438
1       7      49  1.945910
2       3       9  1.098612
3       0       0      -inf
4       2       4  0.693147